project_id = "lhdwmdebrqezcyjnrbnb"

[functions.create-user]
verify_jwt = false

[functions.create-teacher]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-exam]
verify_jwt = false

[functions.pdf-to-exam]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false
